<?php
  $lang['number']		= 'VariabilnÍ symbol';
  $lang['date'] 		= 'Datum';
  $lang['time']			= 'ČÍSLO ÚČTU';
  $lang['due']      = 'Splatnost';
  $lang['transfer']      = 'Typ PŘEVODU';
  $lang['to'] 			= 'ODBĚRATEL';
  $lang['from'] 		= 'DODAVATEL';
  $lang['product'] 		= 'Produkt';
  $lang['qty'] 			= 'KS';
  $lang['price'] 		= 'Cena';
  $lang['discount'] 	= 'Sleva';
  $lang['vat'] 			= 'DPH';
  $lang['total'] 		= 'Celkem';
  $lang['page'] 		= 'Strana';
  $lang['page_of'] 		= 'z';
?>